### ISSUE TITLE
Color not change

### ISSUE THREAD

**Issue by karis** [gitsindonesia/ui-component#96] opened 2023-01-10 22:42 UTC
### Environment

 "@gits-id/ui-nuxt": "^0.14.0"

### Reproduction

here is the code

```
    <VInput
      value="#cb0600"
      wrapper-class="mb-4"
      type="color"
      name="color"
      label="Color"
      placeholder="Color"
    />
```

and here the link :
https://stackblitz.com/edit/github-ycbgbo?file=package.json,app.vue

### Describe the bug

before major update color works fine and smooth in version below :
`    "@gits-id/ui-nuxt": "^0.14.0-alpha.4",`

after update. i found that the color doesn't change even when i try to reload the page.

**Comment by gravitano** [comment] 2023-01-11 03:15
Hi, I think this bug is caused by the behavior change of all form components being uncontrolled by default now. 

Normally, to set an initial value to the input, you just need to set it on the `initialValues` param in the `useForm` hook. But, I also test it in the forked Stackblitz this not working as expected. You can check it here: https://stackblitz.com/edit/github-ycbgbo-qxgzt3?file=package.json,app.vue

Found workaround, we need to set `model-value` prop so the initial value will set.

```html
<template>
        <VInput
          wrapper-class="mb-4"
          type="color"
          name="color"
          label="Color"
          placeholder="Color"
          model-value="#9b1717"
        />
        </template>
```

@gits-gretchelin can you also check this issue?

**Comment by gravitano** [comment] 2023-01-11 11:51
Hi @karis, I just released a new patch `0.14.1`. I think this issue is solved. Give it a try and report back if anything breaks.

You can also check out my forked version of your reproduction here: https://stackblitz.com/edit/github-ycbgbo-qxgzt3?file=package.json,app.vue

**Comment by karis** [comment] 2023-01-11 12:56
good to hear that...

oke let's check it out

**Comment by karis** [comment] 2023-01-11 14:02
hi @gravitano 

i already test. and my apps doesn't run like in alpha version.

when fetching data from db. and set model-value. it's not working.
here is the link.

https://stackblitz.com/edit/github-ycbgbo?file=app.vue

let me know if i miss something on display the data

**Comment by karis** [comment] 2023-01-11 22:23
hi @gravitano 

i found the bug, 
it always execute the `initialValues`.
thats why, the data is not displayed.

check my  link:
https://stackblitz.com/edit/github-ycbgbo?file=app.vue

**Comment by gravitano** [comment] 2023-01-12 05:07
If you are using `useForm` hook, don't to set initial value via `model-value`. You need to set it on the `initialValues` params.

```ts
const { handleSubmit, resetForm } = useForm({
  validationSchema: schema,
  initialValues: {
    vs1: '',
    color: 'red', // <-- set initial value here
  },
});
```

if you want to set value from the db/API, just fetch the data first and then set it to the `initialValues`:
```ts
// fetch data from api
const {data} = await useFetch('/api/color');

const { handleSubmit, resetForm } = useForm({
  validationSchema: schema,
  initialValues: {
    vs1: '',
    color: data.value?.color // <-- set data from api
  },
});
```

**Comment by gravitano** [comment] 2023-01-12 05:07
Check out the working example here: https://stackblitz.com/edit/github-ycbgbo-k19pab?file=server%2Fapi%2Fcolor.ts,app.vue

**Comment by karis** [comment] 2023-01-12 07:52
hi @gravitano 
i think i'll keep this version on my development.
it's a little bit effort times several modul to update the form behavior.  :D

thx for your support.

one last question. when we use model-value if using useForm and initialValues ?

**Comment by gravitano** [comment] 2023-01-12 11:27
I think we also need to adjust the behavior of `modelValue` on `useForm` hook. and the update is already in progress by @gits-gretchelin.

I am closing this issue for now. Feel free to reopen or submit a new issue if anything breaks.

**Closed by gravitano** 2023-01-12 11:27 UTC
Labels: bug
