### ISSUE TITLE
Next page pagination not disabled if only one page

### ISSUE THREAD

**Issue by akbarm23** [gitsindonesia/ui-component#78] opened 2022-12-27 07:20 UTC
VPagination - when the data is only 1 page, the next page button is not disabled

`<VPagination
        v-model="page"
        class="!space-x-3"
        :total-items="totalItems"
        :items-per-page="itemsPerPage"
      />`

**Comment by gravitano** [comment] 2022-12-28 10:16
Hi, thanks for reporting the issue. 

Please provide more info to help me reproduce the issue:
- What's the value of `page`, `totalItems`, and `itemsPerPage`?
- Can you provide screenshot?

**Comment by gravitano** [comment] 2022-12-28 10:18
I've tried reproducing the issue. But, it is working fine in the Storybook canvas. You can see the code I use here: https://github.com/gitsindonesia/ui-component/commit/6c3aaec1f6885e1c77182da8d6746c8557fa6378

Here's the screenshot:
<img width="312" alt="image" src="https://user-images.githubusercontent.com/5087538/209796766-ee8d209c-cbd6-44cb-b650-9c486e6033df.png">

**Comment by gravitano** [comment] 2023-01-04 06:06
I am closing this issue since it is already fixed (reported via DM). Feel free to reopen if this issue still occurs.

**Closed by gravitano** 2023-01-04 06:06 UTC
Labels: bug
