### ISSUE TITLE
Datatable Pagination doesn't work in component with VeeValidate useForm

### ISSUE THREAD

**Issue by gits-gretchelin** [gitsindonesia/ui-component#81] opened 2023-01-03 08:32 UTC
The `items per page` select won't work when used in parent component that uses vee validate `useForm`. `v-model` can be passed and `@update:model-value` does being called with the correct value when selection changes. However, the UI just stuck on "Select" instead of showing actual value. The var being passed in `v-model` also not being updated.

The issue is caused by `VSelect` which is the component being used for the select input. under vee validate `Form` or `useForm`, `VSelect` requires `name` prop to be defined to work properly. 

Issue can be reproduced under storybook by adding this 
```
<v-select
        wrapper-class="mb-4"
        label="Gender"
        v-model='modelVal'
        placeholder="Select your gender"
        :items="genders"
      />
```
into the Validation story with `modelVal` being `const modelVal = ref()`.

**Comment by gravitano** [comment] 2023-01-03 10:59
Sorry for the inconvenience.

Can you share the full reproduction code?

**Comment by gits-gretchelin** [comment] 2023-01-04 02:17
I've forked the lib and create a branch in here : https://github.com/gits-gretchelin/ui-component/blob/repro/issue-81

I've edited this particular storybook's story to showcase the problem in `VDataTablePagination`
https://github.com/gits-gretchelin/ui-component/blob/602a4afe5cf340a8627596873be07c002b1924c0/packages/table/src/VDataTablePagination.stories.ts#L122-L144

And here, I updated `VSelect` story to show that the issue due to VSelect since given the same situation, `VSelect` behave exactly the same, which is _not working_.
https://github.com/gits-gretchelin/ui-component/blob/602a4afe5cf340a8627596873be07c002b1924c0/packages/select/src/VSelect.stories.ts#L165-L236

**Comment by gravitano** [comment] 2023-01-04 05:13
Thanks for the clear reproduction. I confirm that this issue occurs because vee-validate's `useField` requires the `name` prop to be defined.

For now, I think we can replace the `VSelect` with the basic `<select>` input.

**Comment by gravitano** [comment] 2023-01-04 05:47
Maybe in the future, we need to drop `useField` from all forms components if this will cause other issues and give the user freedom to use other validation libraries.

**Comment by karis** [comment] 2023-01-09 11:01
still open bro @gravitano ?

i have same issue when using <VSelect> on vee-validate

Here is what i found. 
VSelect display `[object Object]` in Search Text. it weirds, user have to clear text then type search
<img width="575" alt="Screenshot 2023-01-09 at 18 01 37" src="https://user-images.githubusercontent.com/1776951/211293490-1be1d3bf-1f37-4a2b-ae9d-6d4848ae1563.png">


here the reproduction code : 
`<form class="mt-5 gap-2" @submit="onSubmit">
        <VSelect
          label="Label"
          placeholder="Cari"
          :items="items"
          searchable
          clearable
        />
........
`

**Comment by gravitano** [comment] 2023-01-10 06:12
Hi @karis, sorry for the inconvenience. Yes, the issue is still in fixing.

**Comment by gravitano** [comment] 2023-01-10 07:17
Hi @karis, I just released a new version `0.14.0`, including fixes for this issue. Give it a try and report back if anything breaks.

**Comment by karis** [comment] 2023-01-10 07:30
im so relieved
lets get started new version..

thank you @gravitano..

**Comment by gravitano** [comment] 2023-01-17 07:32
I think now we can close this issue. Feel free to reopen it if it still occurs.

**Closed by gravitano** 2023-01-17 07:32 UTC
Labels: bug
