### ISSUE TITLE
v-autocomplete shows Maximum recursive updates exceeded and input stay behind the modal

### ISSUE THREAD

**Issue by hudaprs** [gitsindonesia/ui-component#133] opened 2023-02-24 09:45 UTC
### Environment

```json
{
  "@gits-id/ui-nuxt": "^0.16.3",
  "vee-validate": "^4.7.3",
}
```

### Reproduction

This is the first time I'm using GITS UI, and it's so good and lightweight.  

I want to report an issue that, I have some form that implementing [Autocomplete](https://gitsindonesia.github.io/ui-component/components/autocomplete.html) and [vee-validate](https://vee-validate.logaretm.com/v4/) as form validation.

```vue
<script setup lang="ts">
const validationSchema = object({
  role: object().required().label('Role')
})
const { handleSubmit } = useForm<IAuthFormChangeRole>({
  validationSchema
})
</script>

<template>
  <form>
    <!-- Role -->
    <app-form-group>
      <v-autocomplete label="Role" name="role" :items="props.roleList" />
    </app-form-group>
  </form>
</template>
```

### Describe the bug

Hi @gravitano , when I start to integrate my code with `vee-validate`, I get some warning message from console that says `Maximum recursive updates exceeded` like so;

![gits-ui-autocomplete](https://user-images.githubusercontent.com/44672728/221143553-546ab4c0-ea41-416c-9548-4bbbefb0fa59.gif)

---

But, when I implement the form **without** `vee-validate` the warning is no longer there, like this;

![gits-ui-autocomplete-no-warn](https://user-images.githubusercontent.com/44672728/221143783-b11eb74f-b204-4a6d-9373-3fd8af7221df.gif)

---

Is this bug or no? Or maybe the problem is inside `vee-validate`, because when I integrating another form beside `Autocomplete` it's working fine. Or maybe someone have same problem with me?

I know this is just a warning, but it say `Maximum recursive updates exceeded`. I fear this warning will impact to the app performance.

Thank you in advance.

### Additional context

P.S, maybe this is related to [Multi Select](https://gitsindonesia.github.io/ui-component/components/multi-select.html) too. The warning stay the same and appear to the console.

Extra issue, when I implement this select option inside modal, it will not overflow, it's stay behind modal. Any suggest?
![image](https://user-images.githubusercontent.com/44672728/221145804-2c0e1375-5f90-4dbf-99f9-dc175a873cbd.png)

The data inside the input is like so, it has 5 data (array of object) inside of it
```json
[
  { "text": "Role 1", "value": 1 },
  { "text": "Role 2", "value": 2 },
  { "text": "Role 3", "value": 3 },
  { "text": "Role 4", "value": 4 },
  { "text": "Role 5", "value": 5 }
]
```

Thank you again.

**Comment by gravitano** [comment] 2023-02-25 05:41
Hi, 

Thanks for the report and sorry for the inconvenience.

Can you create working reproduction via [Stackblitz](https://stackblitz.com/github/gitsindonesia/ui-component/tree/main/starter/nuxt-minimal) so I can investigate more?

Thank you.

**Comment by gravitano** [comment] 2023-03-06 05:16
Hi @hudaprs,

Sorry, this took so long. I think this is because you have a component with the same `name` that connects with `vee-validate` form.

Either change the component's `name` or extract the form into a separate component.

You can check the working solution here: https://stackblitz.com/edit/github-vgvk3n?file=nuxt.config.ts,pages%2Fmultiselect.vue,pages%2Findex.vue

**Comment by hudaprs** [comment] 2023-03-06 11:20
Hi @gravitano ,

Sorry for the late response too.

I already check to make separate component, and make reproduce step as you mention by changing the `name` or extract the form into a separate component. But when I start to reproduce it, the issue still the same, and still throwing the warning.

Also, the same `name` of the input, doesn't make any different when try to change it.

---

As you said, I try to make separate component for the form. You can check the reproduce at this [link](https://stackblitz.com/edit/github-vgvk3n-gtugnf?file=components%2FAutocompleteForm.vue,pages%2Fseparate.vue), and check inside **/separate** path. And still, throwing the warning.

---

I assume it's the rule of the yup that implemented inside `vee-validate` and I try to change from:
```javascript
const validationSchema = object({
  role: object().required().label('Role')
})
```

to:
```javascript
const validationSchema = object()
    .shape({
      text: string().required(),
      value: number().required(),
    })
    .nullable(true)
    .label('Role')
```

But the issue still persist.

---

But if you want to check the real project code, feel free to go my experiment project when implementing GITS UI in:
- [Form that implement vee-validate](https://github.com/hudaprs/go-echo-nuxt/blob/master/components/auth/FormChangeRole.vue). This is separate component;
- [UI that implement the form](https://github.com/hudaprs/go-echo-nuxt/blob/master/pages/auth/login.vue). Form implemented in UI named `auth-form-change-role`.

But you can only see the code, because the project is already integrated with Back-End in [this repository](https://github.com/hudaprs/go-echo) 😁.

---

But maybe if the issue came from `vee-validate` package and when I remove the `vee-validate` from the import statement, it's working fine.

And I will try to experiment to change the validator package to [vuelidate](https://vuelidate-next.netlify.app/) and I'm going to see if the result is the same or not.

Thank you in advance.

**Comment by hudaprs** [comment] 2023-03-07 09:50
Hi @gravitano ,

I'm doing an experiment with a different validator package, I'm using [vuelidate](https://vuelidate-next.netlify.app/) and you can check in this [link](https://stackblitz.com/edit/github-4mhry5?file=pages%2Findex.vue,components%2FForm.vue,nuxt.config.ts).

When using `vuelidate` the warning error for `Maximum recursive updates exceeded` **disappeared**, but returned a different warning like so;
![gits-ui-vuelidate](https://user-images.githubusercontent.com/44672728/223381937-f996ce27-47c8-4ce0-b822-843f78e390a9.gif)

---

When I started experimenting, I found a new issue inside the `v-multiselect` component when the user clicks the `clearable X` button inside the input, will throw this error, this also happened inside the documentation [here](https://gitsindonesia.github.io/ui-component/components/multi-select.html#clearable).
![gits-ui-multi-select-clearable-bug](https://user-images.githubusercontent.com/44672728/223383237-1e0ee5df-7609-4f21-a41d-86680fff27b5.gif)


---

Maybe I'll iterate the issue from the top to bottom;
1. When changing validator package, the `Maximum recursive updates exceeded` is **gone**, but remains the same using `vee-validate`, maybe the UI package is not the problem, but it's in the `vee-validate`.
2. Theres an error when the user starts to clear `v-mutiselect` using `clearable X` button.
3. Label inside selected `v-autocomplete` does not get removed when the value has already been removed.
4. When the user starts to click the `v-autocomplete` for the first time, the component not showing the list, but the user must input letter first, then the list shows up. Maybe it will be better if the user sees the list for the first time user click the `v-autocomplete` input.

---

I will in touch when there's any issue in this components, or maybe in other components.

Thank you in advance.

**Comment by gravitano** [comment] 2023-03-08 09:41
You can ignore the warning if it does not break the application. 

> There's an error when the user starts to clear `v-mutiselect` using the clearable X button.

I can confirm this issue and it will be fixed soon.

Maybe you can create a separate issue for each component to help me track and fixing easily.

**Comment by hudaprs** [comment] 2023-03-08 10:17
Yes, maybe if this does not affect or break the application, maybe the warning should go away then.

Thank you very much, I will make a separate issue soon for other components then.

**Closed** 2023-07-28 04:04 UTC
Labels: bug, good first issue
